//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerMaster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;2hIMsj1pdyJfmpz8yN/EfbSl3pe9QxRx3nm2FTafwzmQnxxB9O35sLANTPIpAmRM8oi730SEYunA0+1T/p9e9EB7iJGwKB7LmaApWk8BRQ5jJwge7tA8wkmciV52jHBzYZk+tHOvuHd+AsMXYB1a/Y/8mpfzjECjU7A0P6ucrVyMkZIxAB0ozHAyABoXi9G57O6tkXAUXqDz6zgRcSIzZ1vkiYoqXKKKxKdXj4HskxzGDwx7w7UF9wDz0Ek2Qtz9CmrROcJhFD22792rqmEYF00WKHw9uuBXaRjEdgmgwcY8loVvFxLOtRMAC7RZiU1oYpTMSsIj7fVh017x63aGzlY8uqDEPz6teeAw52CV1gw1/glzpKJ6DIQBg7MS16xm7pIAh4UciuZUggmhtOrIeD7sT4ZN+MtWwCvV+tf0lnhdAJyEo9rtaoBIicfOA1uge3Pr/QAfXI/Gd8GFryBuKSMJXgknphMVcrp5x+nx7b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MasterServer_pub_prv {
            get {
                return ResourceManager.GetString("MasterServer_pub_prv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;+ShLQhyrcdyqN9KQO5aS4uLZaptlswGz7tIlkJeEIulE/kYvs3o0LQyixudd8j8heCDX50UyH02SaYULyJR3n9mT+JJ6lOKz/rSqjcfTp32Anv09WtEBtsY4nFHgxJTRvRHIhSO600sSzIt4ftRc5jheyBHD6TrNKzJzJoBoxs74Y28kzp2ER0rRqd9h4Sls/dLlHKEzHY0WuQgjEg1eSw8q0OCE4YJxRknadsdGh6dW7CcZuNmJFYL8qFhmUS1Vzy75NEZsEgye0h2oUC/2ediOsHvRZzI2QdDeyweKNK/CRVpXYlDnVi6wFCweWoHrSF5eBESyg7wl/DFC5S4pU28i2gEuqqy3a0D0XCjPuuy9d3ElZUo5NGzZNJUdsFQgjy3tNyX73S6wJ0dG1SZKKbveD+1+Cg+JN5L3RMWRg48KNu/mzLGjjn0xnAI6RS+VIxo9GHjtdtebzmqDzSOUCG7eDubRIH0BwBbsy93+yY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Server1_pub {
            get {
                return ResourceManager.GetString("Server1_pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;s9Mh7p3Eqx6mBfgRRtgmRoK2rXhTvO6STPTlKhyP2V+AiXXUURBHIblMTv+gnjPxfs+xafKnQUDD7PR1TFetDEe0PiVDW4v1E6Hz20f+S2XKXnIucByyhqePEmLC3dLHFmr4OjmCFTGXM1rw9LwggVOUxCIz31ZbhVzSe5ZgO9rHsH9Lk9FW8VDaJS8AmePmvbMW75lGx+7M4YqK7jawayM1daXHgkNQ2/sB6cgtulos6U1EZW4EcM5nDFQvj1HB5/aG5iGRACRDzErUp9J252xXaPFdkZQrX+mpNH2eNdyl2aUHgHAcJ8UTQHbGNELcQt6HlMW/IdgCjhegn+l1CUUoiYOX5zcHc9pvrwkQ8mF3dlv+Yo+L32sYxw6bjlmLWmCa2QGkLZ0KF+ZaShCb/Rp/jnpb30QtHx8pehC3tRMWDsH1mor7ZO2tvoPShAtke2RpUpbhIc/IKTcMg29ULlt/SeMNgB0S/2Gn8YIsGA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Server2_pub {
            get {
                return ResourceManager.GetString("Server2_pub", resourceCulture);
            }
        }
    }
}
